[project]
name = "paper-layout-net-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.0",
    "pymupdf>=1.26.4",
    "pyqt6>=6.9.1",
    "ultralytics>=8.3.206",
]
